<?php

namespace EaredSeal\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-11 at 18:12:00.
 */
class ImageTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Image
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		Image::setInit("/upload/", "/image/");
		$this->object = new Image;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		Image::setInit("", "");
	}

	/**
	 * @covers EaredSeal\Entity\Image::getFileName
	 */
	public function testGetFileName()
	{
		$this->assertEquals("", $this->object->getFileName());

		$this->object = new Image("test.jpg");
		$this->assertEquals("test.jpg", $this->object->getFileName());
	}

	/**
	 * @covers EaredSeal\Entity\Image::getUrl
	 */
	public function testGetUrl()
	{
		$this->assertEquals("", $this->object->getUrl());

		$this->object = new Image("test.jpg");
		$this->assertEquals("/image/test.jpg", $this->object->getUrl());
	}

	/**
	 * @covers EaredSeal\Entity\Image::getFile
	 */
	public function testGetFile()
	{
		$this->assertEquals("", $this->object->getFile());

		$this->object = new Image("test.jpg");
		$this->assertEquals("/upload/test.jpg", $this->object->getFile());
	}

	/**
	 * @covers EaredSeal\Entity\Image::__toString
	 * @todo   Implement test__toString().
	 */
	public function test__toString()
	{
		$this->object = new Image("test.jpg");
		$this->assertEquals("/image/test.jpg", $this->object->__toString());
	}

}